CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    external_id VARCHAR2(50),
    user_type VARCHAR2(20),
    status VARCHAR2(20),
    risk_score NUMBER(5,2),
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
	CONSTRAINT chk_users_type CHECK (user_type IN ('CUSTOMER', 'MERCHANT','OPERATOR')),
	CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'BLOCKED', 'CLOSED'))
);
CREATE TABLE accounts (
    account_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    account_number VARCHAR2(20) UNIQUE,
    currency_code CHAR(3) DEFAULT 'USD',
    balance NUMBER(18,2) DEFAULT 0,
    available_balance NUMBER(18,2) DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'ACTIVE',
    version_number NUMBER DEFAULT 1,
    created_at DATE DEFAULT SYSDATE,
    updated_at DATE DEFAULT SYSDATE,
    CONSTRAINT pk_account PRIMARY KEY (account_id),
	CONSTRAINT chk_accounts_currency CHECK (currency_code IN ('USD', 'EUR', 'GBP')),
	CONSTRAINT chk_accounts_status CHECK (status IN ('ACTIVE', 'BLOCKED', 'CLOSED')),
    CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);
CREATE TABLE payment_transaction (
    transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    from_account_id NUMBER NOT NULL,
    to_account_id NUMBER NOT NULL,
    transaction_type VARCHAR2(20) NOT NULL,
    amount NUMBER(18,2) NOT NULL,
    currency_code CHAR(3) NOT NULL,
    status VARCHAR2(20) NOT NULL,
    channel VARCHAR2(20) NOT NULL,
    country_code CHAR(2),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    processed_at TIMESTAMP,
    reference_id VARCHAR2(100),
    batch_id NUMBER,
    device_type VARCHAR2(50),
    ip_address VARCHAR2(45),
    merchant_category VARCHAR2(100),
    CONSTRAINT pk_payment_transaction PRIMARY KEY (transaction_id),
    CONSTRAINT fk_pt_from_account FOREIGN KEY (from_account_id) REFERENCES accounts(account_id),
    CONSTRAINT fk_pt_to_account FOREIGN KEY (to_account_id) REFERENCES accounts(account_id),
    CONSTRAINT chk_pt_type CHECK (transaction_type IN ('TRANSFER','PAYMENT','REFUND')),
    CONSTRAINT chk_pt_status CHECK (status IN ('PENDING','COMPLETED','FAILED')),
    CONSTRAINT chk_pt_channel CHECK (channel IN ('WEB','API','MOBILE')),
    CONSTRAINT chk_pt_amount CHECK (amount > 0)
);
CREATE TABLE transaction_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    transaction_id NUMBER NOT NULL,
    old_status VARCHAR2(20),
    new_status VARCHAR2(20),
    changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    changed_by VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_transaction_audit PRIMARY KEY (audit_id),
    CONSTRAINT fk_ta_transaction FOREIGN KEY (transaction_id) REFERENCES payment_transaction(transaction_id),
    CONSTRAINT chk_ta_status CHECK (new_status IN ('PENDING','COMPLETED','FAILED'))
);
CREATE TABLE daily_account_balance (
    account_id NUMBER NOT NULL,
    balance_date DATE NOT NULL,
    opening_balance NUMBER(18,2) NOT NULL,
    closing_balance NUMBER(18,2) NOT NULL,
    total_incoming NUMBER(18,2) DEFAULT 0 NOT NULL,
    total_outgoing NUMBER(18,2) DEFAULT 0 NOT NULL,
    transaction_count NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT pk_daily_account_balance PRIMARY KEY (account_id, balance_date),
    CONSTRAINT fk_dab_account FOREIGN KEY (account_id) REFERENCES accounts(account_id)
);
CREATE TABLE aml_alert (
    alert_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER NOT NULL,
    account_id NUMBER,
    alert_type VARCHAR2(30) NOT NULL,
    alert_score NUMBER(10,4) NOT NULL,
    threshold_value NUMBER(10,4),
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    generated_by VARCHAR2(50) DEFAULT 'PYTHON_ENGINE' NOT NULL,
    CONSTRAINT pk_aml_alert PRIMARY KEY (alert_id),
    CONSTRAINT fk_aml_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_aml_account FOREIGN KEY (account_id) REFERENCES accounts(account_id),
    CONSTRAINT chk_aml_type CHECK (alert_type IN ('HIGH_VOLUME','STRUCTURING','OUTLIER')),
    CONSTRAINT chk_aml_status CHECK (status IN ('OPEN','REVIEWED','CLOSED'))
);
CREATE TABLE batch_process_log (
    batch_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    started_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    status VARCHAR2(20) NOT NULL,
    processed_records NUMBER DEFAULT 0,
    error_count NUMBER DEFAULT 0,
    CONSTRAINT pk_batch_process_log PRIMARY KEY (batch_id),
    CONSTRAINT chk_bpl_status CHECK (status IN ('STARTED','COMPLETED','FAILED'))
);
